// This is an example workflow generated by create-libretto.
// Feel free to modify or delete it entirely and create your own workflows.

import { workflow } from "libretto";
import { log } from "../shared/utils.js";

export const starRepo = workflow("star-repo", async ({ page }) => {
  log("Navigating to Libretto repo...");
  await page.goto("https://github.com/saffron-health/libretto");
  await page.locator('button:has-text("Star")').click();
  log("Starred the repo!");
});
